<?php

namespace PAI\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    
    public function findAllByPostId($postId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PAIBlogBundle:Comment p WHERE p.post = :postId')
            ->setParameter('postId', $postId)
            ->getResult();
    }
    
}