pai_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PAIBlogBundle:Default:index }

PAIBlogBundle_post:
    resource: "@PAIBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post
    
PAIBlogBundle_comment:
    resource: "@PAIBlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
